## Giới thiệu về Deep learning with Pytorch

- Pytorch là 1 framework giúp xây dựng và huấn luyện neural networks
- Cách dùng tương đồng với numpy array
- Có hỗ trợ GPUs
- Autograd

### Tensors

- Các tính toán của neural networks bản chất là các phép toán đại số tuyến tính trên các *tensors*, một khái niệm tổng quát của ma trận
- Các ví dụ:
    - Vector: 1D tensor
    - Matrix: 2D tensor
    - Image RGB: 3D tensor

In [1]:
import torch

In [2]:
def activation(x):
    """
    Sigmoid activation function
    """
    return 1/(1 + torch.exp(-x)) 

In [3]:
torch.manual_seed(7)
features = torch.randn((1, 5)) # 1 row 5 cols, Normal distribution
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [4]:
features.shape

torch.Size([1, 5])

$$ y = f(\sum_{i} w_i * x_i + b)$$

In [5]:
y = activation(torch.sum(features * weights) + bias)

In [6]:
y

tensor([[0.1595]])

#### Dot 2 vectors

In [7]:
try:
    torch.mm(features, weights) # Lỗi vì 1x5 không thể dot với 1 x 5
except:
    print("Lỗi shape rồi: ", features.shape, weights.shape)

Lỗi shape rồi:  torch.Size([1, 5]) torch.Size([1, 5])


Có một số cách để thay đổi kích thước tensor:
- weights.reshape(a, b) : **Có thể** sẽ return 1 tensor với **view mới**, **cũng có thể** sẽ return 1 tensor **clone** 
- weights.resize_(a, b) : return **tensor weights**, với kích thước khác. 
    - Nếu kích thước mới nhỏ hơn số elements của weights, các elements thừa sẽ bị remove (nhưng ko từ memory)
    - Nếu new shape lớn hơn, các elements mới sẽ chưa được khởi tạo trong memory
    - Dấu "_" : Ký hiệu **in-place**
- weights.view(a, b) : return 1 tensor với view mới (a, b) nhưng data là của tensor cũ, yêu cầu số element của shape mới phải bằng với số element của shape cũ

In [8]:
y = activation(torch.mm(features, weights.transpose(1, 0)) + bias)
y

tensor([[0.1595]])

In [9]:
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
y

tensor([[0.1595]])

$$y = f_{2}(f_{1} ({\vec{x}} W1) W2 )$$

In [10]:
torch.manual_seed(7)

features = torch.randn((1, 3))

n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [11]:
y = activation(activation(features.mm(W1) + B1).mm(W2) + B2)

### Torch to Numpy và ngược lại

In [12]:
import numpy as np

In [13]:
a = np.random.rand(4, 3)

In [14]:
a

array([[0.09320691, 0.09754042, 0.54467495],
       [0.7084906 , 0.5090933 , 0.80506533],
       [0.12931879, 0.63622229, 0.35966323],
       [0.84986948, 0.86675794, 0.63929543]])

In [15]:
b = torch.from_numpy(a)

In [16]:
b

tensor([[0.0932, 0.0975, 0.5447],
        [0.7085, 0.5091, 0.8051],
        [0.1293, 0.6362, 0.3597],
        [0.8499, 0.8668, 0.6393]], dtype=torch.float64)

In [17]:
b.mul_(2) # inplace multiplication

tensor([[0.1864, 0.1951, 1.0893],
        [1.4170, 1.0182, 1.6101],
        [0.2586, 1.2724, 0.7193],
        [1.6997, 1.7335, 1.2786]], dtype=torch.float64)

In [18]:
a

array([[0.18641382, 0.19508083, 1.0893499 ],
       [1.4169812 , 1.01818661, 1.61013066],
       [0.25863757, 1.27244458, 0.71932645],
       [1.69973896, 1.73351587, 1.27859086]])

memory **được share giữa numpy & torch tensor**, nên sau khi thực hiện phép nhân, numpy array cũng thay đổi