# Building a Private database

Can we construct a query which doesn't change no matter who we remove from the database ? 

## Simple Database

In [1]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5 # Kind of positive, negative feature
db

tensor([0, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8)

# Project: Generate Parallel Databases

Key to the definition of differenital privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in order to check this, we must construct what we term **"parallel databases" which are simply databases with one entry removed.**

In this first project, I want you to create a list of every parallel database to the one currently contained in the "db" variable. Then, I want you to create a function which both:

- creates the initial database (db)
- creates all parallel databases

In [2]:
dbs = []
for remove_idx in range(num_entries):
    dbs.append(torch.cat(
        (db[:remove_idx],db[remove_idx+1:])
    ))

In [3]:
len(dbs)

5000

In [4]:
def get_parallel_db(db, remove_idx):
    return torch.cat((db[:remove_idx], db[remove_idx+1:]))

In [5]:
def get_parallel_dbs(db):
    dbs = []
    for remove_idx in range(len(db)):
        dbs.append(get_parallel_db(db, remove_idx))
    return dbs

In [6]:
dbs = get_parallel_dbs(db)

In [7]:
len(dbs)

5000

In [8]:
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    return db, pdbs

In [9]:
db, pdbs = create_db_and_parallels(20)

In [10]:
db

tensor([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
       dtype=torch.uint8)

In [11]:
pdbs

[tensor([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,